version: '3.8'

services:
  node_backend:
    container_name: rest_api
    image: rest_api:0.0.4
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=restapi_db
      - PGUSER=kenan
      - PGPASSWORD=kenan1234*
      - PGHOST=node_db
    depends_on:
      - node_db

  pgadmin4:
    container_name: pgadmin4
    image : "dpage/pgadmin4:latest"
    ports :
      - "5050:5050"
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=fullstackankara@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=kenan1234*
      - PGHOST=node_db
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image : "postgres:14"
    ports :
      - "5432:5432"
    environment:
      - POSTGRES_USER=kenan
      - POSTGRES_PASSWORD=kenan1234*
      - POSTGRES_DB=restapi_db
    volumes:
      - nps_data:/var/lib/postgresql/data
  

volumes:
  nps_data: {}
  pgadmin: {}
    